---

services:

  tsidp:
    image: ghcr.io/tailscale/tsidp:latest
    container_name: tsidp
    volumes:
      - tsidp-data:/data
    environment:
      - TAILSCALE_USE_WIP_CODE=1 # tsidp is experimental - needed while version <1.0.0
      - TS_STATE_DIR=/data # store persistent tsnet and tsidp state
      - TS_HOSTNAME=idp # Hostname on tailnet (becomes idp.your-tailnet.ts.net)
      - TSIDP_ENABLE_STS=1 # Enable OAuth token exchange
      - TS_AUTHKEY=${TSIDP_TS_AUTHKEY}
    networks:
      - caddy_net
    restart: unless-stopped

  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxydata:/data
    environment:
      - TSDPROXY_AUTHKEY=${TSDPROXY_AUTHKEY}
      - TSDPROXY_HOSTNAME=${TSDPROXY_HOSTNAME}
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

  rss:
    image: freshrss/freshrss:latest
    container_name: rss
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "rss"
    environment:
      - TZ=America/Chicago
      - CRON_MIN='*/5'
      - OIDC_ENABLED=0
      - OIDC_PROVIDER_METADATA_URL=${FRESHRSS_OIDC_PROVIDER_METADATA_URL}
      - OIDC_CLIENT_ID=${FRESHRSS_OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${FRESHRSS_OIDC_CLIENT_SECRET}
      - OIDC_CLIENT_CRYPTO_KEY=${FRESHRSS_OIDC_CLIENT_CRYPTO_KEY}
      - OIDC_REMOTE_USER_CLAIM=preferred_username
      - OIDC_SCOPES=openid profile email
      - OIDC_X_FORWARDED_HEADERS=X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
    ports:
      - 8080:80
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    networks:
      - caddy_net
    restart: unless-stopped

  caddy:
    image: centcom/caddy-route53:local
    build:
      context: .
      dockerfile: caddy/Dockerfile
    container_name: caddy
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "caddy"
    hostname: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./www:/usr/share/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      - caddy_net

  golink:
    image: ghcr.io/tailscale/golink:main
    container_name: golink
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "go"
    restart: unless-stopped
    user: root
    environment:
      - TS_AUTHKEY=${TSDPROXY_AUTHKEY}
    volumes:
      - /opt/golink/data:/home/nonroot
    networks:
      - caddy_net

volumes:
  tsidp-data:
  tsdproxydata:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    external: true
