---

services:

  docktail:
    image: ghcr.io/marvinvr/docktail:latest
    container_name: docktail-automated
    environment:
      - TAILSCALE_OAUTH_CLIENT_ID=${TAILSCALE_OAUTH_CLIENT_ID}
      - TAILSCALE_OAUTH_CLIENT_SECRET=${TAILSCALE_OAUTH_CLIENT_SECRET}
      - DEFAULT_SERVICE_TAGS=tag:docktail-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale:/var/run/tailscale
    restart: unless-stopped

  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxydata:/data
    environment:
      - TSDPROXY_AUTHKEY=${TSDPROXY_AUTHKEY}
      - TSDPROXY_HOSTNAME=${TSDPROXY_HOSTNAME}
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

  tsidp:
    image: ghcr.io/tailscale/tsidp:latest
    container_name: tsidp
    volumes:
      - tsidp-data:/data
    environment:
      - TAILSCALE_USE_WIP_CODE=1 # tsidp is experimental - needed while version <1.0.0
      - TS_STATE_DIR=/data # store persistent tsnet and tsidp state
      - TSIDP_ENABLE_STS=1 # Enable OAuth token exchange
    labels:
      - docktail.service.enable=true
      - docktail.service.name=idp
      - docktail.service.port=80
      - docktail.service.service-port=443
    networks:
      - caddy_net
    restart: unless-stopped

  rss:
    image: freshrss/freshrss:latest
    container_name: rss
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "rss"
    environment:
      - TZ=America/Chicago
      - CRON_MIN=*/5
    ports:
      - 8080:80
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    networks:
      - caddy_net
    restart: unless-stopped

  caddy:
    image: centcom/caddy-route53:local
    build:
      context: .
      dockerfile: caddy/Dockerfile
    container_name: caddy
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "caddy"
    hostname: caddy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./www:/usr/share/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      - caddy_net

  golink:
    image: ghcr.io/tailscale/golink:main
    container_name: golink
    labels:
      - docktail.service.enable=true
      - docktail.service.name=go
      - docktail.service.port=80
      - docktail.service.service-port=443
    restart: unless-stopped
    user: root
    volumes:
      - /opt/golink/data:/home/nonroot
    networks:
      - caddy_net

volumes:
  tsidp-data:
  tsdproxydata:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    external: true
